name: Build, Test, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Test
        run: |
          cd frontend
          npm run test
#       - name: Deploy to EC2 or EKS
#         uses: appleboy/ssh-action@master
#         with:
#           host: <your EC2 or EKS instance IP address or hostname>
#           username: <your IAM user's username>
#           password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
#           script: |
#             cd /path/to/your/application
#             git pull
#             npm install
#             npm run build
