name: Build, Test, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
#       - name: Test
#         run: |
#           cd frontend
#           npm run test
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-35-174-208-142.compute-1.amazonaws.com
          username: Administrator
          private-key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd "/apps/nets-chat-app/frontend/"
            git pull
            npm install
            npm run build
